---
title: "Datos EcoBici"
format: html
editor: visual
---

## Análisis de datos Programa ECOBICI

### Idea:

Este proyecto intenta abordar un análisis completo del programa [ECOBICI](https://data.buenosaires.gob.ar/dataset/bicicletas-publicas) a través de 3 fuentes de datos:

Usuarios

Estaciones

Recorridos

## Instalamos librerias

```{r librerias, warning=FALSE}

rm(list = ls()) 

###################################################################################
# Instalamos librerías de trabajo

for( package in c("shiny", "datasets", "shinydashboard", "DT", "lubridate","kableExtra","tidyverse", "plotly","leaflet","sf","sp")) {
  
  if (!require(package, character.only = T, quietly = T)) {
    install.packages(package, repos = "http://cran.us.r-project.org")
    library(package, character.only = T)
  }
}



###################################################################################


```

## Descargamos bases de trabajo

```{r descargas, warning=FALSE}

# leemos archivo de trabajo (USUARIOS)

linkusu <- "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/transporte-y-obras-publicas/bicicletas-publicas/usuarios_ecobici_2023.csv"

datausu <- read.csv(linkusu, encoding = "UTF-8")

data <- datausu %>%
  head(10)

#limpieza

datausu <- datausu %>%
  mutate("Genero" = case_when( genero_usuario == "MALE" ~ "Masculino",
                               genero_usuario == "FEMALE" ~ "Femenino",
                               TRUE ~ "Otro"),
         "Fecha" = ymd(fecha_alta),
         "Mes" = month(Fecha, label = TRUE),
         "Día" = wday(Fecha,label = TRUE, abbr = FALSE),
         "Hora" = hms(hora_alta),
         "Edad" = as.numeric(as.character(edad_usuario)),
         "Año" = year(fecha_alta),
         "EdadRec" = case_when(Edad >= 0 & Edad < 15 ~ "Menores de 15",
                               Edad >= 15 & Edad < 20 ~ "de 15 hasta 20",
                            Edad >= 20 & Edad < 25 ~ "de 20 hasta 25",
                            Edad >= 25 & Edad < 30 ~ "de 25 hasta 30",
                            Edad >= 30 & Edad < 35 ~ "de 30 hasta 35",
                            Edad >= 35 & Edad < 40 ~ "de 35 hasta 40",
                            Edad >= 40 & Edad < 45 ~ "de 40 hasta 45",
                            Edad >= 45 & Edad < 50 ~ "de 45 hasta 50",
                            Edad >= 50 & Edad < 55 ~ "de 50 hasta 55",
                            TRUE ~ "Mayores de 55"))

Tabla1 <- datausu %>%
  group_by(Genero) %>%
  summarise(Total = n()) %>%
  mutate("%" = round(Total/sum(Total)*100,2))



###################################################################################


```

```{r descargas, warning=FALSE}

# leemos archivo de trabajo (RECORRIDOS)

link<- ("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/transporte-y-obras-publicas/bicicletas-publicas/recorridos-realizados-2022.zip")

temp <- tempfile()
download.file(link,temp)
data <- read.csv(unz(temp, "trips_2021.csv"), encoding = "UTF-8")
unlink(temp)

# limpieza data

data1 <- data %>%
  head(20)

# data %>%
#   str()

# limpieza duración recorrido

data$duracion_recorrido <- sub(",", "", data$duracion_recorrido, fixed = TRUE)

data <- data %>%
  mutate("Duración_recorrido" = as.numeric(as.character(data$duracion_recorrido)),
         "Fecha_origen" = ymd_hms(data$fecha_origen_recorrido),
         "Fecha_destino" = ymd_hms(data$fecha_destino_recorrido),
         "Duración_real" = Fecha_destino - Fecha_origen,
         "Mes_origen" = month(Fecha_origen, label = TRUE),
         "Día_origen" = wday(Fecha_origen, label = TRUE, abbr = FALSE))



```

```{r descargas, warning=FALSE}

##(PRUEBA DESCARGA ESTACIONES)

link <- "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/transporte-y-obras-publicas/estaciones-bicicletas-publicas/nuevas-estaciones-bicicletas-publicas.csv"
dataest <- read.csv(link)

##(PRUEBA LEVANTA BASES DE ESTACIONES YA DESCARGADAS)

estaciones <- st_read("data/estaciones-de-bicicletas-zip/IE-Estaciones.shp")

##(DESCARGA MAPA BARRIOS CABA)

barrios <- st_read('https://bitsandbricks.github.io/data/CABA_barrios.geojson')


estaciones <- estaciones %>% 
  mutate("Región" = case_when(COMUNA %in% c("COMUNA 12","COMUNA 13","COMUNA 14","COMUNA 2") ~ "Norte",
                              COMUNA %in% c("COMUNA 5","COMUNA 6","COMUNA 7","COMUNA 10","COMUNA 11","COMUNA 15","COMUNA 1","COMUNA 3") ~ "Centro",
                              COMUNA %in% c("COMUNA 8","COMUNA 4","COMUNA 9") ~ "Sur",
                              COMUNA == "" ~ "Sin Informar"))

tabla_1 <- estaciones %>% 
  select(COMUNA) %>% 
  group_by(COMUNA) %>% 
  summarize(Total = n())
  
  
```
